version: '3.8'
services:
  kafka:
    image: bitnami/kafka:3.7.0
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=yes
      - KAFKA_BROKER_USER=meuusuario
      - KAFKA_BROKER_PASSWORD=minhasenha
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuvwx
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami/kafka
    restart: unless-stopped

volumes:
  kafka_data:

